# NEURONS Configuration File

# Neuron Parameters
neuron:
  tau_m: 20.0                    # Membrane time constant (ms)
  v_rest: -70.0                  # Resting potential (mV)
  v_threshold: -55.0             # Spike threshold (mV)
  v_reset: -75.0                 # Reset potential (mV)
  refractory_period: 2.0         # Refractory period (ms)
  resistance: 10.0               # Membrane resistance (MÎ©)
  adaptation_beta: 0.1           # Spike frequency adaptation

# STDP Parameters (Triplet)
stdp:
  tau_plus: 16.8                 # Pre-synaptic trace (ms)
  tau_minus: 33.7                # Post-synaptic trace (ms)
  tau_x: 101.0                   # Triplet pre trace (ms)
  tau_y: 125.0                   # Triplet post trace (ms)
  A_plus: 0.01                   # Potentiation amplitude
  A_minus: -0.012                # Depression amplitude
  w_min: 0.0                     # Minimum weight
  w_max: 1.0                     # Maximum weight

# Voltage-Dependent STDP
voltage_stdp:
  theta_plus: -45.0              # Potentiation threshold (mV)
  theta_minus: -70.0             # Depression threshold (mV)
  A_LTP: 0.008                   # LTP amplitude
  A_LTD: 0.010                   # LTD amplitude

# Synaptic Scaling
synaptic_scaling:
  tau_scale: 3600.0              # Scaling time constant (s)
  target_rate: 10.0              # Target firing rate (Hz)

# Neuromodulation
neuromodulation:
  dopamine:
    baseline: 4.0                # Baseline DA level (Hz)
    gain: 1.0                    # Gain for RPE
    tau: 200.0                   # Time constant (ms)
  serotonin:
    baseline: 2.0                # Baseline 5-HT level
    tau: 500.0                   # Time constant (ms)
  norepinephrine:
    baseline: 3.0                # Baseline NE level
    tau: 300.0                   # Time constant (ms)
  acetylcholine:
    baseline: 5.0                # Baseline ACh level
    tau: 400.0                   # Time constant (ms)

# Neural Oscillations
oscillations:
  theta:
    frequency: 6.0               # Theta frequency (Hz)
    amplitude: 5.0               # Theta amplitude (mV)
  gamma:
    frequency: 60.0              # Gamma frequency (Hz)
    amplitude: 2.0               # Gamma amplitude (mV)
  coupling_strength: 0.3         # Phase-amplitude coupling

# Elastic Weight Consolidation
ewc:
  lambda_: 5000.0                # EWC regularization strength
  fisher_samples: 200            # Samples for Fisher computation
  online_mode: true              # Online EWC

# Network Architecture
architecture:
  sparsity: 0.05                 # Target sparsity (5% active)
  connectivity: 0.2              # Connection probability
  weight_init: "uniform"         # Weight initialization
  use_bias: false                # Use bias terms

# Optimization
optimization:
  enable_simd: true              # SIMD vectorization
  enable_quantization: true      # INT8 quantization
  enable_sparse: true            # Sparse computation
  event_driven: true             # Event-driven processing

# Training
training:
  learning_rate: 0.001
  batch_size: 32
  epochs: 10
  dt: 1.0                        # Time step (ms)
  presentation_time: 50.0        # Input presentation (ms)

# Evaluation
evaluation:
  monitor_energy: true
  monitor_sparsity: true
  monitor_forgetting: true
  save_checkpoints: true
  checkpoint_interval: 5

# Logging
logging:
  level: "INFO"
  save_logs: true
  log_dir: "logs"
  tensorboard: true
