from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="neuronsv2",
    version="2.0.0",
    author="Oluwatosin Abioye Afolabi",
    author_email="afolabi@genovotech.com",
    description="NEURONSv2: Revolutionary Neural Architecture - 28× faster than Transformers with O(n) attention",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/tafolabi009/NEURONS_NEW",
    packages=find_packages(exclude=["benchmarks", "examples", "data", "checkpoints", ".history"]),
    include_package_data=True,
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "Operating System :: OS Independent",
    ],
    keywords=[
        "neural-networks",
        "deep-learning",
        "transformers",
        "attention-mechanism",
        "biologically-inspired",
        "neuromorphic",
        "few-shot-learning",
        "meta-learning",
        "continual-learning",
        "edge-ai",
        "efficient-ml",
    ],
    python_requires=">=3.8",
    install_requires=[
        "numpy>=1.24.0",
        "scipy>=1.10.0",
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.3.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "tqdm>=4.65.0",
        "numba>=0.57.0",
        "pyyaml>=6.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "pytest-cov>=4.1.0",
            "black>=23.0.0",
            "flake8>=6.0.0",
            "mypy>=1.4.0",
            "isort>=5.12.0",
        ],
        "viz": [
            "plotly>=5.14.0",
            "tensorboard>=2.13.0",
        ],
        "all": [
            "pytest>=7.4.0",
            "pytest-cov>=4.1.0",
            "black>=23.0.0",
            "flake8>=6.0.0",
            "mypy>=1.4.0",
            "isort>=5.12.0",
            "plotly>=5.14.0",
            "tensorboard>=2.13.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "neuronsv2-train=training.train_loop:main",
            "neuronsv2-benchmark=training.efficiency_benchmark:main",
        ],
    },
    project_urls={
        "Bug Reports": "https://github.com/tafolabi009/NEURONS_NEW/issues",
        "Source": "https://github.com/tafolabi009/NEURONS_NEW",
        "Documentation": "https://github.com/tafolabi009/NEURONS_NEW#readme",
    },
)
